import {store} from ('./app/store')
import {cakeActions} from ('./features/Cake/cakeSlice')
import {icecreamActions} from ('./features/Icecream/icecreamSlice')

console.log('Initial State', store.getState())
const unsubscribe= store.subscribe(()=>{console.log('Updated State', store.getState())})
store.dispatch(cakeActions.ordered())
store.dispatch(cakeActions.ordered())
store.dispatch(cakeActions.ordered())
store.dispatch(cakeActions.restocked(3))
store.dispatch(icecreamActions.icecreamorder())
store.dispatch(icecreamActions.icecreamorder())
store.dispatch(icecreamActions.icecreamrestocked(2))
unsubscribe()